# Generated by Django 5.0.4 on 2024-04-16 02:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=150)),
                ('imagen', models.ImageField(null=True, upload_to=core.models.get_file_path)),
                ('descripcion', models.CharField(max_length=500)),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('precioOferta', models.FloatField()),
                ('status', models.BooleanField(default=False, help_text='0=Default, 1Hidden')),
                ('tag', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMascota',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('TipoMascota', models.CharField(max_length=50, verbose_name='Gato/Perro')),
            ],
        ),
    ]
