# Generated by Django 5.0.4 on 2024-04-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_producto_preciooferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='status',
            field=models.BooleanField(default=False, help_text='0=inhabilitado, 1 habilitado'),
        ),
    ]
