# Generated by Django 5.0.4 on 2024-04-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precioOferta',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
